version: '3'

services:
  app:
    container_name: node-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      PORT: 3000
      
  keycloak:
    image: quay.io/keycloak/keycloak:22.0.0
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    command:
      - start-dev